global:
  scrape_interval: 3s
  evaluation_interval: 3s

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: apicontagem-http
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:5101']

